# This is a basic workflow to help you get started with Actions

name: Deploy Navi-Gateway to Container Registry

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  release_version: 1.0.1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup .NET Core 5.0.x
      - name: Setup .NET Core SDK '5.0.x'
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
      
      # Release to Nuget
      - name: Deploy to Container Registry
        env:
          LOGGER_VERSION: ${{ env.release_version }}
        run: |
          dotnet pack
          dotnet nuget push LoggerLibrary/bin/Debug/NaviLoggerService.${{ env.release_version }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json